name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["16"]

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379

    env:
      NODE_ENV: ci
      PORT: 3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }} # Ensure node version for checkout

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }} # Ensure node version for setup

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Start server
        run: |
          nohup npm run start &
          sleep 3

      - name: Run tests
        run: npm run test
